WIP

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-PRJDIR="$THISDIR/app"
+PRJDIR="$THISDIR/project"
 ENV="hack"
 
 set -euo pipefail
@@ -14,8 +14,6 @@ cat <<ENDHELP
            restore      Creates or updates your venv with your requirements.txt
            build        Run static analyis (mypy) and linting
            default      Setup, Restore, Build, citest
-           migrate      Remove your .db file and runs schema
-           seed         Populates the database with fake data made with faker
            citest       Runs pytest to test the flask endpoints
            dev          Runs a development flask server
         After clone, run setup
@@ -33,7 +31,6 @@ function build_build() {
 }
 
 function build_citest() {
-    run_cmd seed
      pytest -vv
 }
 
@@ -42,7 +39,7 @@ function build_test() {
 }
 
 function build_restore() {
-    if ! which python | grep -w "$ENV" > /dev/null ; then
+    if ! which python3 | grep -w "$ENV" > /dev/null ; then
         python3 -m venv "$ENV"
     fi
     source "$ENV/bin/activate"
@@ -64,13 +61,17 @@ function build_default() {
 }
 
 function build_setup() {
-    command python --version > /dev/null || { echo "Missing python - you need to install it." ; exit 1 ; }
+    command python3 --version > /dev/null || { echo "Missing python - you need to install it." ; exit 1 ; }
     command virtualenv --version > /dev/null || { echo "Missing virtualenv - you need to install it." ; exit 1 ; }
     command pip --version > /dev/null || { echo "Missing pip - you need to install it." ; exit 2 ; }
 }
 
-function build_dev() {
-    : # python ./run.py
+function build_assembler() {
+    python ./project/assembler/assembler.py "$@"
+}
+
+function build_lexer() {
+    python ./project/lexer/JackAnalyzer.py "$@"
 }
 
 cmd="${1:-default}"
